
drop table user_roles if exists;
drop table users if exists;

create table users (
  user_name         varchar(15) not null primary key,
  user_pass         varchar(15) not null
);

create table user_roles (
  user_name         varchar(15) not null,
  role_name         varchar(15) not null,
  primary key (user_name, role_name),
  foreign key (user_name) references users(user_name)
);

insert into users values ('kodecamp','kodecamp');
insert into users values ('kcamp','kcamp');

insert into user_roles values ('kodecamp','ADMIN');
insert into user_roles values ('kcamp','USER');


insert into STUDENTS (id, name, address, active) values (1, 'Tabbie', 'Selkirk', false);
insert into STUDENTS (id, name, address, active) values (2, 'Massimo', 'Saint-Denis', false);
insert into STUDENTS (id, name, address, active) values (3, 'Vail', 'Pag-asa', false);
insert into STUDENTS (id, name, address, active) values (4, 'Agosto', 'Qaryat ad Da‘īs', true);
insert into STUDENTS (id, name, address, active) values (5, 'Barrett', 'Kérkyra', true);
insert into STUDENTS (id, name, address, active) values (6, 'Thomasin', 'Patrang', false);
insert into STUDENTS (id, name, address, active) values (7, 'Della', 'Cookshire-Eaton', false);
insert into STUDENTS (id, name, address, active) values (8, 'Carmella', 'Yovon', false);
insert into STUDENTS (id, name, address, active) values (9, 'Susan', 'Kutorejo', false);
insert into STUDENTS (id, name, address, active) values (10, 'Moyna', 'Évreux', false);
insert into STUDENTS (id, name, address, active) values (11, 'Fairfax', 'Văn Giang', false);
insert into STUDENTS (id, name, address, active) values (12, 'Beauregard', 'Wakapuken', false);
insert into STUDENTS (id, name, address, active) values (13, 'Shirlene', 'Purbalingga', true);
insert into STUDENTS (id, name, address, active) values (14, 'Ariel', 'Tarlac City', true);
insert into STUDENTS (id, name, address, active) values (15, 'Allissa', 'Arthur’s Town', true);
insert into STUDENTS (id, name, address, active) values (16, 'Dagmar', 'Lipa City', true);
insert into STUDENTS (id, name, address, active) values (17, 'Bettina', 'Doumen', true);
insert into STUDENTS (id, name, address, active) values (18, 'Chadd', 'Shuangkou', true);
insert into STUDENTS (id, name, address, active) values (19, 'Nadeen', 'Qiaogu', true);
insert into STUDENTS (id, name, address, active) values (20, 'Mommy', 'Kromasan', true);
insert into STUDENTS (id, name, address, active) values (21, 'Darcy', 'Czarna', true);
insert into STUDENTS (id, name, address, active) values (22, 'Harrietta', 'Columbus', true);
insert into STUDENTS (id, name, address, active) values (23, 'Elly', 'Raleigh', true);
insert into STUDENTS (id, name, address, active) values (24, 'Ariadne', 'Dadian', true);
insert into STUDENTS (id, name, address, active) values (25, 'Ilsa', 'Xiadu', false);
insert into STUDENTS (id, name, address, active) values (26, 'Jackie', 'Shengtang', false);
insert into STUDENTS (id, name, address, active) values (27, 'Yale', 'Yumbo', true);
insert into STUDENTS (id, name, address, active) values (28, 'Concordia', 'Ciervo Petiso', true);
insert into STUDENTS (id, name, address, active) values (29, 'Siusan', 'Vale de São Cosme', true);
insert into STUDENTS (id, name, address, active) values (30, 'Guinevere', 'Rāwandūz', false);
insert into STUDENTS (id, name, address, active) values (31, 'Kaylil', 'Sadkowice', false);
insert into STUDENTS (id, name, address, active) values (32, 'Bar', 'Kista', false);
insert into STUDENTS (id, name, address, active) values (33, 'Shurlock', 'Mounlapamôk', true);
insert into STUDENTS (id, name, address, active) values (34, 'Rahal', 'Pedra', true);
insert into STUDENTS (id, name, address, active) values (35, 'Anders', 'Khānewāl', true);
insert into STUDENTS (id, name, address, active) values (36, 'Andros', 'Sibanicú', false);
insert into STUDENTS (id, name, address, active) values (37, 'Loy', 'Lembung Tengah', false);
insert into STUDENTS (id, name, address, active) values (38, 'Shane', 'Maizuru', true);
insert into STUDENTS (id, name, address, active) values (39, 'Lorens', 'Sugihmukti', false);
insert into STUDENTS (id, name, address, active) values (40, 'Norris', 'Mambago', true);
insert into STUDENTS (id, name, address, active) values (41, 'Frankie', 'Yaqian', false);
insert into STUDENTS (id, name, address, active) values (42, 'Tandie', 'Shengshan', true);
insert into STUDENTS (id, name, address, active) values (43, 'Libbi', 'Reda', false);
insert into STUDENTS (id, name, address, active) values (44, 'Germana', 'Chilecito', false);
insert into STUDENTS (id, name, address, active) values (45, 'Germain', 'Sérifos', false);
insert into STUDENTS (id, name, address, active) values (46, 'Christian', 'Mangaratiba', false);
insert into STUDENTS (id, name, address, active) values (47, 'Petrina', 'Aserrí', true);
insert into STUDENTS (id, name, address, active) values (48, 'Sacha', 'Kalmar', false);
insert into STUDENTS (id, name, address, active) values (49, 'Hernando', 'Hitoyoshi', true);
insert into STUDENTS (id, name, address, active) values (50, 'Emlynne', 'São Paio de Seide', true);
insert into STUDENTS (id, name, address, active) values (51, 'Clemens', 'Milín', false);
insert into STUDENTS (id, name, address, active) values (52, 'Clarance', 'Öjebyn', false);
insert into STUDENTS (id, name, address, active) values (53, 'Hedda', 'Bosanski Brod', true);
insert into STUDENTS (id, name, address, active) values (54, 'Damaris', 'Xingxi', false);
insert into STUDENTS (id, name, address, active) values (55, 'Windy', 'Solntsevo', true);
insert into STUDENTS (id, name, address, active) values (56, 'Penny', 'Jacareí', true);
insert into STUDENTS (id, name, address, active) values (57, 'Reggi', 'Pohang', true);
insert into STUDENTS (id, name, address, active) values (58, 'Karlotta', 'Kajar', true);
insert into STUDENTS (id, name, address, active) values (59, 'Koressa', 'Bretaña', false);
insert into STUDENTS (id, name, address, active) values (60, 'Pauly', 'Shihudang', true);
insert into STUDENTS (id, name, address, active) values (61, 'Worden', 'Tianyu', true);
insert into STUDENTS (id, name, address, active) values (62, 'Helen', 'Al Fūlah', false);
insert into STUDENTS (id, name, address, active) values (63, 'Dollie', 'Surkh Bilandī', true);
insert into STUDENTS (id, name, address, active) values (64, 'Othilie', 'Akita Shi', true);
insert into STUDENTS (id, name, address, active) values (65, 'Lane', 'Mori', true);
insert into STUDENTS (id, name, address, active) values (66, 'Quintana', 'Godong', false);
insert into STUDENTS (id, name, address, active) values (67, 'Marianna', 'Markala', true);
insert into STUDENTS (id, name, address, active) values (68, 'Doloritas', 'Mapalad', true);
insert into STUDENTS (id, name, address, active) values (69, 'Diana', 'Xiang Ngeun', true);
insert into STUDENTS (id, name, address, active) values (70, 'Jamal', 'Lupao', false);
insert into STUDENTS (id, name, address, active) values (71, 'Elyssa', 'Lacombe', false);
insert into STUDENTS (id, name, address, active) values (72, 'Winifield', 'Wassa-Akropong', true);
insert into STUDENTS (id, name, address, active) values (73, 'Joyan', 'Mat-i', false);
insert into STUDENTS (id, name, address, active) values (74, 'Leo', 'Rustenburg', false);
insert into STUDENTS (id, name, address, active) values (75, 'Kimmie', 'Paris La Défense', true);
insert into STUDENTS (id, name, address, active) values (76, 'Etti', 'Huangbayi', false);
insert into STUDENTS (id, name, address, active) values (77, 'Alyce', 'Woto', false);
insert into STUDENTS (id, name, address, active) values (78, 'Hillyer', 'Erjia', false);
insert into STUDENTS (id, name, address, active) values (79, 'Vincenty', 'Uwajima', false);
insert into STUDENTS (id, name, address, active) values (80, 'Corena', 'Hougong', true);
insert into STUDENTS (id, name, address, active) values (81, 'Adelice', 'Tha Wang Pha', false);
insert into STUDENTS (id, name, address, active) values (82, 'Nerty', 'Binjai', false);
insert into STUDENTS (id, name, address, active) values (83, 'Wendel', 'Kass Wollof', true);
insert into STUDENTS (id, name, address, active) values (84, 'Shamus', 'Shangganshan', false);
insert into STUDENTS (id, name, address, active) values (85, 'Gracia', 'Żarnów', false);
insert into STUDENTS (id, name, address, active) values (86, 'Alicia', 'Panolan', false);
insert into STUDENTS (id, name, address, active) values (87, 'Ricardo', 'Trubchevsk', true);
insert into STUDENTS (id, name, address, active) values (88, 'Aridatha', 'Goodlands', false);
insert into STUDENTS (id, name, address, active) values (89, 'Daphne', 'Pirassununga', false);
insert into STUDENTS (id, name, address, active) values (90, 'Mauricio', 'Ufa', true);
insert into STUDENTS (id, name, address, active) values (91, 'Mellie', 'La Jagua de Ibirico', true);
insert into STUDENTS (id, name, address, active) values (92, 'Robin', 'Oro Timur', true);
insert into STUDENTS (id, name, address, active) values (93, 'Pincas', 'Pirallahı', false);
insert into STUDENTS (id, name, address, active) values (94, 'Asa', 'Prnjavor', true);
insert into STUDENTS (id, name, address, active) values (95, 'Madelon', 'Baqiao', true);
insert into STUDENTS (id, name, address, active) values (96, 'Esme', 'Monção', false);
insert into STUDENTS (id, name, address, active) values (97, 'Miguel', 'San Juan Ermita', true);
insert into STUDENTS (id, name, address, active) values (98, 'Jolyn', 'Tagapul-an', false);
insert into STUDENTS (id, name, address, active) values (99, 'Adoree', 'Akaki', false);
insert into STUDENTS (id, name, address, active) values (100, 'Robbert', 'Arrap’i', true);
insert into STUDENTS (id, name, address, active) values (101, 'Violet', 'Hejiang', false);
insert into STUDENTS (id, name, address, active) values (102, 'Timofei', 'Pergamos', false);
insert into STUDENTS (id, name, address, active) values (103, 'Lorens', 'Lhoknga', true);
insert into STUDENTS (id, name, address, active) values (104, 'Waylin', 'Xishui', true);
insert into STUDENTS (id, name, address, active) values (105, 'Amabelle', 'Manzë', false);
insert into STUDENTS (id, name, address, active) values (106, 'Briana', 'Tacoma', true);
insert into STUDENTS (id, name, address, active) values (107, 'Fanni', 'Ronov nad Doubravou', false);
insert into STUDENTS (id, name, address, active) values (108, 'Luise', 'Boucinha', false);
insert into STUDENTS (id, name, address, active) values (109, 'Kathy', 'Chřibská', true);
insert into STUDENTS (id, name, address, active) values (110, 'Korry', 'Shangying', false);
insert into STUDENTS (id, name, address, active) values (111, 'Erskine', 'Mineralnye Vody', false);
insert into STUDENTS (id, name, address, active) values (112, 'Pavla', 'Jiahe', true);
insert into STUDENTS (id, name, address, active) values (113, 'Barbara', 'Lamduan', true);
insert into STUDENTS (id, name, address, active) values (114, 'Auroora', 'Franca', true);
insert into STUDENTS (id, name, address, active) values (115, 'Rozanna', 'Shengtang', true);
insert into STUDENTS (id, name, address, active) values (116, 'Henri', 'Neresnytsya', false);
insert into STUDENTS (id, name, address, active) values (117, 'Had', 'Galis Dua', true);
insert into STUDENTS (id, name, address, active) values (118, 'Keefe', 'Zhamao', false);
insert into STUDENTS (id, name, address, active) values (119, 'Duane', 'Changshan', true);
insert into STUDENTS (id, name, address, active) values (120, 'Micaela', 'Panenggoede', true);
insert into STUDENTS (id, name, address, active) values (121, 'Eugenius', 'Nikita', true);
insert into STUDENTS (id, name, address, active) values (122, 'Ibrahim', 'Vide', true);
insert into STUDENTS (id, name, address, active) values (123, 'Garald', 'Gongchang', true);
insert into STUDENTS (id, name, address, active) values (124, 'Ruperta', 'Ashibetsu', true);
insert into STUDENTS (id, name, address, active) values (125, 'Stanly', 'Hallstahammar', true);
insert into STUDENTS (id, name, address, active) values (126, 'Vyky', 'Dunkerque', false);
insert into STUDENTS (id, name, address, active) values (127, 'Devlen', 'Luxia', false);
insert into STUDENTS (id, name, address, active) values (128, 'Harwell', 'Boise', true);
insert into STUDENTS (id, name, address, active) values (129, 'Chantal', 'Esteio', false);
insert into STUDENTS (id, name, address, active) values (130, 'Tanny', 'Batelov', true);
insert into STUDENTS (id, name, address, active) values (131, 'Janella', 'Rabak', true);
insert into STUDENTS (id, name, address, active) values (132, 'Linc', 'Xiangyang', true);
insert into STUDENTS (id, name, address, active) values (133, 'Maximilian', 'Tân Sơn', true);
insert into STUDENTS (id, name, address, active) values (134, 'Rosana', 'Lordegān', false);
insert into STUDENTS (id, name, address, active) values (135, 'Trev', 'Pimentel', false);
insert into STUDENTS (id, name, address, active) values (136, 'Brietta', 'Lebowakgomo', true);
insert into STUDENTS (id, name, address, active) values (137, 'Ford', 'Scottsdale', false);
insert into STUDENTS (id, name, address, active) values (138, 'Danyelle', 'Spodnja Hajdina', true);
insert into STUDENTS (id, name, address, active) values (139, 'Emilio', 'Pante Raja', true);
insert into STUDENTS (id, name, address, active) values (140, 'Ameline', 'Kuytun', false);
insert into STUDENTS (id, name, address, active) values (141, 'Timofei', 'Quebrada de Arena', false);
insert into STUDENTS (id, name, address, active) values (142, 'Art', 'Loutrós', true);
insert into STUDENTS (id, name, address, active) values (143, 'Davis', 'Sumurasin', true);
insert into STUDENTS (id, name, address, active) values (144, 'Correy', 'Lidian', false);
insert into STUDENTS (id, name, address, active) values (145, 'Dino', 'Gayny', false);
insert into STUDENTS (id, name, address, active) values (146, 'Avram', 'Nemuro', true);
insert into STUDENTS (id, name, address, active) values (147, 'Kinsley', 'Morón', false);
insert into STUDENTS (id, name, address, active) values (148, 'Vittorio', 'Shizukuishi', true);
insert into STUDENTS (id, name, address, active) values (149, 'Malia', 'Omsukchan', false);
insert into STUDENTS (id, name, address, active) values (150, 'Jobina', 'Trondheim', true);
insert into STUDENTS (id, name, address, active) values (151, 'Waite', 'Pul-e Sangī', false);
insert into STUDENTS (id, name, address, active) values (152, 'Dita', 'Dingcheng', true);
insert into STUDENTS (id, name, address, active) values (153, 'Killy', 'Berdorf', true);
insert into STUDENTS (id, name, address, active) values (154, 'Zara', 'Daru', true);
insert into STUDENTS (id, name, address, active) values (155, 'Scarface', 'Helsingborg', false);
insert into STUDENTS (id, name, address, active) values (156, 'Tandi', 'Panjerrejo', true);
insert into STUDENTS (id, name, address, active) values (157, 'Emmye', 'Petropavlovsk', false);
insert into STUDENTS (id, name, address, active) values (158, 'Britney', 'Serra D''El Rei', false);
insert into STUDENTS (id, name, address, active) values (159, 'Joycelin', 'Qingban', true);
insert into STUDENTS (id, name, address, active) values (160, 'Jammal', 'Esperanza', false);
insert into STUDENTS (id, name, address, active) values (161, 'Blanca', 'Akim Oda', true);
insert into STUDENTS (id, name, address, active) values (162, 'Bren', 'Gensi', true);
insert into STUDENTS (id, name, address, active) values (163, 'Tanny', 'Ban Talat Nua', false);
insert into STUDENTS (id, name, address, active) values (164, 'Heath', 'Oslo', false);
insert into STUDENTS (id, name, address, active) values (165, 'Zane', 'Dashiqiao', true);
insert into STUDENTS (id, name, address, active) values (166, 'Korry', 'Castillos', true);
insert into STUDENTS (id, name, address, active) values (167, 'Gabriel', 'Šimanovci', false);
insert into STUDENTS (id, name, address, active) values (168, 'Dotti', 'Chernomorskiy', false);
insert into STUDENTS (id, name, address, active) values (169, 'Rosamond', 'Arcos', false);
insert into STUDENTS (id, name, address, active) values (170, 'Liza', 'Billings', false);
insert into STUDENTS (id, name, address, active) values (171, 'Trudy', 'Otuke', true);
insert into STUDENTS (id, name, address, active) values (172, 'Angelia', 'Saint-Denis', false);
insert into STUDENTS (id, name, address, active) values (173, 'Jamie', 'Mulyosari', true);
insert into STUDENTS (id, name, address, active) values (174, 'Berkley', 'Karlskoga', true);
insert into STUDENTS (id, name, address, active) values (175, 'Sybil', 'Duko', true);
insert into STUDENTS (id, name, address, active) values (176, 'Colas', 'Ignacio Zaragoza', false);
insert into STUDENTS (id, name, address, active) values (177, 'Prue', 'La Estrella', false);
insert into STUDENTS (id, name, address, active) values (178, 'Ari', 'Tagum', true);
insert into STUDENTS (id, name, address, active) values (179, 'Christiano', 'Taitung City', false);
insert into STUDENTS (id, name, address, active) values (180, 'Jerrome', 'Mucuri', false);
insert into STUDENTS (id, name, address, active) values (181, 'Yalonda', 'Sarov', true);
insert into STUDENTS (id, name, address, active) values (182, 'Eveleen', 'Dióni', false);
insert into STUDENTS (id, name, address, active) values (183, 'Patti', 'Rafaï', true);
insert into STUDENTS (id, name, address, active) values (184, 'Shaina', 'Fukuoka-shi', true);
insert into STUDENTS (id, name, address, active) values (185, 'Gertrude', 'Traganón', false);
insert into STUDENTS (id, name, address, active) values (186, 'Eric', 'Gällivare', true);
insert into STUDENTS (id, name, address, active) values (187, 'Curr', 'Araxá', false);
insert into STUDENTS (id, name, address, active) values (188, 'Kata', 'Montréal-Est', true);
insert into STUDENTS (id, name, address, active) values (189, 'Sheffield', 'Kurashiki', true);
insert into STUDENTS (id, name, address, active) values (190, 'Aylmar', 'Irkutsk', true);
insert into STUDENTS (id, name, address, active) values (191, 'Kerry', 'San Isidro', true);
insert into STUDENTS (id, name, address, active) values (192, 'Vere', 'Katy', false);
insert into STUDENTS (id, name, address, active) values (193, 'Minor', 'Santa Lucía', true);
insert into STUDENTS (id, name, address, active) values (194, 'Guntar', 'Rtyně v Podkrkonoší', true);
insert into STUDENTS (id, name, address, active) values (195, 'Abbi', 'Banī Zayd', true);
insert into STUDENTS (id, name, address, active) values (196, 'Pansy', 'Strasbourg', false);
insert into STUDENTS (id, name, address, active) values (197, 'Randall', 'Krajan Sumurtawang', false);
insert into STUDENTS (id, name, address, active) values (198, 'Dolf', 'Bizerte', false);
insert into STUDENTS (id, name, address, active) values (199, 'Tyler', 'Ushirombo', false);
insert into STUDENTS (id, name, address, active) values (200, 'Sigrid', 'Maromme', false);
insert into STUDENTS (id, name, address, active) values (201, 'Hadrian', 'Pelabuhan Dagang', false);
insert into STUDENTS (id, name, address, active) values (202, 'Bellina', 'Debrecen', true);
insert into STUDENTS (id, name, address, active) values (203, 'Alphard', 'Itagibá', false);
insert into STUDENTS (id, name, address, active) values (204, 'Briant', 'Querobamba', false);
insert into STUDENTS (id, name, address, active) values (205, 'Adoree', 'Kai', false);
insert into STUDENTS (id, name, address, active) values (206, 'Austin', 'Seka', true);
insert into STUDENTS (id, name, address, active) values (207, 'Cory', 'Daping', true);
insert into STUDENTS (id, name, address, active) values (208, 'Antonia', 'Sémé', false);
insert into STUDENTS (id, name, address, active) values (209, 'Jeffy', 'Shestakovo', false);
insert into STUDENTS (id, name, address, active) values (210, 'Kaitlynn', 'Idanre', false);
insert into STUDENTS (id, name, address, active) values (211, 'Hanni', 'Palmar de Varela', true);
insert into STUDENTS (id, name, address, active) values (212, 'Field', 'Baruunturuun', true);
insert into STUDENTS (id, name, address, active) values (213, 'Jennee', 'Rafaï', false);
insert into STUDENTS (id, name, address, active) values (214, 'Mylo', 'Nizhniy Bestyakh', true);
insert into STUDENTS (id, name, address, active) values (215, 'Roy', 'Itararé', true);
insert into STUDENTS (id, name, address, active) values (216, 'Anitra', 'Vryburg', false);
insert into STUDENTS (id, name, address, active) values (217, 'Ina', 'Taozhuang', false);
insert into STUDENTS (id, name, address, active) values (218, 'Eberhard', 'Mariquita', false);
insert into STUDENTS (id, name, address, active) values (219, 'Claudell', 'Kapotnya', true);
insert into STUDENTS (id, name, address, active) values (220, 'Bondon', 'Houzhai', false);
insert into STUDENTS (id, name, address, active) values (221, 'Carina', 'Gaio', true);
insert into STUDENTS (id, name, address, active) values (222, 'Sioux', 'Maria Aurora', false);
insert into STUDENTS (id, name, address, active) values (223, 'Joe', 'Nanbao', true);
insert into STUDENTS (id, name, address, active) values (224, 'Demetra', 'Užice', false);
insert into STUDENTS (id, name, address, active) values (225, 'Elli', 'Tygda', false);
insert into STUDENTS (id, name, address, active) values (226, 'Conney', 'Karatsu', false);
insert into STUDENTS (id, name, address, active) values (227, 'Brandea', 'Pitangui', true);
insert into STUDENTS (id, name, address, active) values (228, 'Sarajane', 'Karangori', true);
insert into STUDENTS (id, name, address, active) values (229, 'Bert', 'Akouda', false);
insert into STUDENTS (id, name, address, active) values (230, 'Orren', 'Korosten’', false);
insert into STUDENTS (id, name, address, active) values (231, 'Frazer', 'Manlucahoc', false);
insert into STUDENTS (id, name, address, active) values (232, 'Romain', 'Krajan Tambakrejo', false);
insert into STUDENTS (id, name, address, active) values (233, 'Sansone', 'Yangcun', false);
insert into STUDENTS (id, name, address, active) values (234, 'Sorcha', 'Tarrafal', false);
insert into STUDENTS (id, name, address, active) values (235, 'Albie', 'Zaria', true);
insert into STUDENTS (id, name, address, active) values (236, 'Trumann', 'Francisco Villa', true);
insert into STUDENTS (id, name, address, active) values (237, 'Dana', 'Hammam-Lif', false);
insert into STUDENTS (id, name, address, active) values (238, 'Audie', 'Kislyakovskaya', false);
insert into STUDENTS (id, name, address, active) values (239, 'Boote', 'Maevatanana', true);
insert into STUDENTS (id, name, address, active) values (240, 'Margeaux', 'Huangtian', true);
insert into STUDENTS (id, name, address, active) values (241, 'Loraine', 'Staroshcherbinovskaya', true);
insert into STUDENTS (id, name, address, active) values (242, 'Kettie', 'Hirado', false);
insert into STUDENTS (id, name, address, active) values (243, 'Jeannette', 'Yanyang', true);
insert into STUDENTS (id, name, address, active) values (244, 'Luca', 'Gaoqiao', false);
insert into STUDENTS (id, name, address, active) values (245, 'Andra', 'Taboão da Serra', false);
insert into STUDENTS (id, name, address, active) values (246, 'Marsh', 'Skillingaryd', false);
insert into STUDENTS (id, name, address, active) values (247, 'Nertie', 'Cedynia', true);
insert into STUDENTS (id, name, address, active) values (248, 'Kahlil', 'Neya', true);
insert into STUDENTS (id, name, address, active) values (249, 'Chad', 'Dayushu', false);
insert into STUDENTS (id, name, address, active) values (250, 'Loren', 'Ngaruawahia', false);
insert into STUDENTS (id, name, address, active) values (251, 'Athene', 'Huacheng', false);
insert into STUDENTS (id, name, address, active) values (252, 'Pru', 'Nanterre', true);
insert into STUDENTS (id, name, address, active) values (253, 'Nester', 'Port Glaud', false);
insert into STUDENTS (id, name, address, active) values (254, 'Ginni', 'Castelo de Vide', true);
insert into STUDENTS (id, name, address, active) values (255, 'Hall', 'Mlawat', true);
insert into STUDENTS (id, name, address, active) values (256, 'Roy', 'Zhetian', true);
insert into STUDENTS (id, name, address, active) values (257, 'Udell', 'Tras Cerros', true);
insert into STUDENTS (id, name, address, active) values (258, 'Troy', 'Bunutan', false);
insert into STUDENTS (id, name, address, active) values (259, 'Lezlie', 'Peimei', true);
insert into STUDENTS (id, name, address, active) values (260, 'Juditha', 'Stockholm', false);
insert into STUDENTS (id, name, address, active) values (261, 'Killie', 'Holguín', true);
insert into STUDENTS (id, name, address, active) values (262, 'Celestia', 'Las Matas de Santa Cruz', true);
insert into STUDENTS (id, name, address, active) values (263, 'Verna', 'Morrito', true);
insert into STUDENTS (id, name, address, active) values (264, 'Davy', 'Las Vegas', true);
insert into STUDENTS (id, name, address, active) values (265, 'Ephraim', 'Lyubimets', true);
insert into STUDENTS (id, name, address, active) values (266, 'Juana', 'Haljala', true);
insert into STUDENTS (id, name, address, active) values (267, 'Jay', 'Baima', false);
insert into STUDENTS (id, name, address, active) values (268, 'Mylo', 'Don Mueang', true);
insert into STUDENTS (id, name, address, active) values (269, 'Nolan', 'Yên Lạc', true);
insert into STUDENTS (id, name, address, active) values (270, 'Tris', 'Chŏngju', false);
insert into STUDENTS (id, name, address, active) values (271, 'Alexa', 'Nova Petrópolis', true);
insert into STUDENTS (id, name, address, active) values (272, 'Amalea', 'Greensboro', true);
insert into STUDENTS (id, name, address, active) values (273, 'Oswell', '‘Afak', false);
insert into STUDENTS (id, name, address, active) values (274, 'Chrisy', 'Lampitak', false);
insert into STUDENTS (id, name, address, active) values (275, 'Rowan', 'Teculután', true);
insert into STUDENTS (id, name, address, active) values (276, 'Kiele', 'Labuhanlalar', false);
insert into STUDENTS (id, name, address, active) values (277, 'Dierdre', 'Shatian', false);
insert into STUDENTS (id, name, address, active) values (278, 'Erie', 'Palcamayo', true);
insert into STUDENTS (id, name, address, active) values (279, 'Caria', 'Al Fashn', true);
insert into STUDENTS (id, name, address, active) values (280, 'Filippo', 'Gävle', true);
insert into STUDENTS (id, name, address, active) values (281, 'Ellwood', 'Sochaux', false);
insert into STUDENTS (id, name, address, active) values (282, 'Kerr', 'Doña Remedios Trinidad', false);
insert into STUDENTS (id, name, address, active) values (283, 'Travers', 'Almoínhas Velhas', false);
insert into STUDENTS (id, name, address, active) values (284, 'Harp', 'Lile', true);
insert into STUDENTS (id, name, address, active) values (285, 'Granger', 'Hong Kong', true);
insert into STUDENTS (id, name, address, active) values (286, 'Corrianne', 'San Martin', false);
insert into STUDENTS (id, name, address, active) values (287, 'Garwin', 'Colonia Nicolich', true);
insert into STUDENTS (id, name, address, active) values (288, 'Xaviera', 'Mobaye', true);
insert into STUDENTS (id, name, address, active) values (289, 'Valli', 'Banjar Taro Kelod', true);
insert into STUDENTS (id, name, address, active) values (290, 'Franzen', 'Kambingan', true);
insert into STUDENTS (id, name, address, active) values (291, 'Dolf', 'Jandira', true);
insert into STUDENTS (id, name, address, active) values (292, 'Arnie', 'Voloka', true);
insert into STUDENTS (id, name, address, active) values (293, 'Ortensia', 'Hegarsari', true);
insert into STUDENTS (id, name, address, active) values (294, 'Wilbert', 'Provatás', true);
insert into STUDENTS (id, name, address, active) values (295, 'Karmen', 'Siao', false);
insert into STUDENTS (id, name, address, active) values (296, 'Brew', 'Lebak Timur', true);
insert into STUDENTS (id, name, address, active) values (297, 'Ollie', 'Yarumela', false);
insert into STUDENTS (id, name, address, active) values (298, 'Lin', 'Arrentela', true);
insert into STUDENTS (id, name, address, active) values (299, 'Ramona', 'Tuanshansi', false);
insert into STUDENTS (id, name, address, active) values (300, 'Bev', 'Ngondokandawu', false);
insert into STUDENTS (id, name, address, active) values (301, 'Constantino', 'Puerto Parra', true);
insert into STUDENTS (id, name, address, active) values (302, 'Ansel', 'Xihe', false);
insert into STUDENTS (id, name, address, active) values (303, 'Alleyn', 'Damascus', false);
insert into STUDENTS (id, name, address, active) values (304, 'Bennie', 'Puro Pinget', true);
insert into STUDENTS (id, name, address, active) values (305, 'Toma', 'Chat Trakan', true);
insert into STUDENTS (id, name, address, active) values (306, 'Roberta', 'Ciilat', false);
insert into STUDENTS (id, name, address, active) values (307, 'Radcliffe', 'Shulan', false);
insert into STUDENTS (id, name, address, active) values (308, 'Ursuline', 'Łopuszno', true);
insert into STUDENTS (id, name, address, active) values (309, 'Gray', 'Berovo', false);
insert into STUDENTS (id, name, address, active) values (310, 'Jacquenetta', 'Kuanghe', true);
insert into STUDENTS (id, name, address, active) values (311, 'Vernon', 'Munsan', false);
insert into STUDENTS (id, name, address, active) values (312, 'Herb', 'Kotablolong', false);
insert into STUDENTS (id, name, address, active) values (313, 'Corabelle', 'Santa Fe', false);
insert into STUDENTS (id, name, address, active) values (314, 'Penelope', 'Lindavista', true);
insert into STUDENTS (id, name, address, active) values (315, 'Britni', 'Wielgie', false);
insert into STUDENTS (id, name, address, active) values (316, 'Helli', 'San José', true);
insert into STUDENTS (id, name, address, active) values (317, 'Nathalia', 'Dadoupu', true);
insert into STUDENTS (id, name, address, active) values (318, 'Alva', 'Sulak', false);
insert into STUDENTS (id, name, address, active) values (319, 'Lyssa', 'Aya', true);
insert into STUDENTS (id, name, address, active) values (320, 'Fay', 'Enrile', false);
insert into STUDENTS (id, name, address, active) values (321, 'Madelyn', 'Hroznětín', false);
insert into STUDENTS (id, name, address, active) values (322, 'Hamish', 'Nkandla', true);
insert into STUDENTS (id, name, address, active) values (323, 'Travus', 'Qinghe', false);
insert into STUDENTS (id, name, address, active) values (324, 'Hesther', 'Pamungguan', false);
insert into STUDENTS (id, name, address, active) values (325, 'Brnaby', 'Zambujeira', false);
insert into STUDENTS (id, name, address, active) values (326, 'Lorette', 'Monticello', true);
insert into STUDENTS (id, name, address, active) values (327, 'Dame', 'Kajaani', true);
insert into STUDENTS (id, name, address, active) values (328, 'Mohammed', 'Tomado', true);
insert into STUDENTS (id, name, address, active) values (329, 'Dale', 'Liujiagou', true);
insert into STUDENTS (id, name, address, active) values (330, 'Aurea', 'Gunung Talang', false);
insert into STUDENTS (id, name, address, active) values (331, 'Yvon', 'Philadelphia', false);
insert into STUDENTS (id, name, address, active) values (332, 'Fredia', 'Vichuga', false);
insert into STUDENTS (id, name, address, active) values (333, 'Laure', 'Metahāra', true);
insert into STUDENTS (id, name, address, active) values (334, 'Ettie', 'Lokot’', true);
insert into STUDENTS (id, name, address, active) values (335, 'Ramsay', 'Potiskum', true);
insert into STUDENTS (id, name, address, active) values (336, 'Linell', 'Tianhu', true);
insert into STUDENTS (id, name, address, active) values (337, 'Deirdre', 'Matmata', false);
insert into STUDENTS (id, name, address, active) values (338, 'Claiborne', 'Genang', false);
insert into STUDENTS (id, name, address, active) values (339, 'Rosalind', 'Kafr Miṣr', true);
insert into STUDENTS (id, name, address, active) values (340, 'Bianka', 'Regla', true);
insert into STUDENTS (id, name, address, active) values (341, 'Idaline', 'Dzhalilabad', true);
insert into STUDENTS (id, name, address, active) values (342, 'Dahlia', 'Rasshevatskaya', true);
insert into STUDENTS (id, name, address, active) values (343, 'Maurise', 'Pangu', true);
insert into STUDENTS (id, name, address, active) values (344, 'Lamar', 'Kasturi', true);
insert into STUDENTS (id, name, address, active) values (345, 'Alasteir', 'Ma’an', false);
insert into STUDENTS (id, name, address, active) values (346, 'Ellene', 'Khon Kaen', false);
insert into STUDENTS (id, name, address, active) values (347, 'Cathyleen', 'Kugri', true);
insert into STUDENTS (id, name, address, active) values (348, 'Merl', 'Pereiro', false);
insert into STUDENTS (id, name, address, active) values (349, 'Corabelle', 'Strasbourg', false);
insert into STUDENTS (id, name, address, active) values (350, 'Doris', 'Privlaka', true);
insert into STUDENTS (id, name, address, active) values (351, 'Jerome', 'Nangkasari', true);
insert into STUDENTS (id, name, address, active) values (352, 'Adriena', 'Granja', false);
insert into STUDENTS (id, name, address, active) values (353, 'Valentine', 'Beizheng', false);
insert into STUDENTS (id, name, address, active) values (354, 'Orv', 'Rakitovo', false);
insert into STUDENTS (id, name, address, active) values (355, 'Hyman', 'Ar Ramthā', false);
insert into STUDENTS (id, name, address, active) values (356, 'Hollis', '‘Ayn an Nasr', true);
insert into STUDENTS (id, name, address, active) values (357, 'Devon', 'Xinzhai', true);
insert into STUDENTS (id, name, address, active) values (358, 'Gui', 'Tercena', false);
insert into STUDENTS (id, name, address, active) values (359, 'Rona', 'Sriwing', true);
insert into STUDENTS (id, name, address, active) values (360, 'Marcile', 'Gesikan', true);
insert into STUDENTS (id, name, address, active) values (361, 'Fredericka', 'Masohi', false);
insert into STUDENTS (id, name, address, active) values (362, 'Barbette', 'Conceição da Abóboda', false);
insert into STUDENTS (id, name, address, active) values (363, 'Susy', 'Sidaohezi', false);
insert into STUDENTS (id, name, address, active) values (364, 'Johnny', 'Suvorov', true);
insert into STUDENTS (id, name, address, active) values (365, 'Gussy', 'Sitampiky', false);
insert into STUDENTS (id, name, address, active) values (366, 'Andre', 'Francisco Sarabia', true);
insert into STUDENTS (id, name, address, active) values (367, 'Edi', 'Bell Ville', true);
insert into STUDENTS (id, name, address, active) values (368, 'Arielle', 'Injīl', false);
insert into STUDENTS (id, name, address, active) values (369, 'Peria', 'Mopti', true);
insert into STUDENTS (id, name, address, active) values (370, 'Dorri', 'Tim', true);
insert into STUDENTS (id, name, address, active) values (371, 'Beatriz', 'Pingtian', true);
insert into STUDENTS (id, name, address, active) values (372, 'Aurthur', 'Mansôa', true);
insert into STUDENTS (id, name, address, active) values (373, 'Wittie', 'Santa Cruz De Tenerife', false);
insert into STUDENTS (id, name, address, active) values (374, 'Conny', 'Wensu', false);
insert into STUDENTS (id, name, address, active) values (375, 'Ruthanne', 'Pantano do Sul', false);
insert into STUDENTS (id, name, address, active) values (376, 'Simonette', 'Ejmiatsin', true);
insert into STUDENTS (id, name, address, active) values (377, 'Hobart', 'Jamaica', false);
insert into STUDENTS (id, name, address, active) values (378, 'Tuesday', 'Shisui', false);
insert into STUDENTS (id, name, address, active) values (379, 'Catharine', 'Gadžin Han', true);
insert into STUDENTS (id, name, address, active) values (380, 'Galvin', 'Dois Córregos', false);
insert into STUDENTS (id, name, address, active) values (381, 'Tristan', 'Ar Rawnah', false);
insert into STUDENTS (id, name, address, active) values (382, 'Reynard', 'Mekarsari', true);
insert into STUDENTS (id, name, address, active) values (383, 'Arlette', 'Kumbo', true);
insert into STUDENTS (id, name, address, active) values (384, 'Sandro', 'Koukkuniemi', true);
insert into STUDENTS (id, name, address, active) values (385, 'Alfreda', 'Mikhaylov', false);
insert into STUDENTS (id, name, address, active) values (386, 'Nelie', 'Sipocot', false);
insert into STUDENTS (id, name, address, active) values (387, 'Doroteya', 'Novovasylivka', false);
insert into STUDENTS (id, name, address, active) values (388, 'Siana', 'Qingping', true);
insert into STUDENTS (id, name, address, active) values (389, 'Shanie', 'Kuala Lumpur', true);
insert into STUDENTS (id, name, address, active) values (390, 'Pace', 'Le Cannet', false);
insert into STUDENTS (id, name, address, active) values (391, 'Flossi', 'Quilo-quilo', true);
insert into STUDENTS (id, name, address, active) values (392, 'Rochelle', 'Stopnica', false);
insert into STUDENTS (id, name, address, active) values (393, 'Loreen', 'Penápolis', false);
insert into STUDENTS (id, name, address, active) values (394, 'Anna-maria', 'Derviçian', true);
insert into STUDENTS (id, name, address, active) values (395, 'Samuel', 'Kangping', true);
insert into STUDENTS (id, name, address, active) values (396, 'Marji', 'Umm as Summāq', true);
insert into STUDENTS (id, name, address, active) values (397, 'Hillary', 'Bedayu', true);
insert into STUDENTS (id, name, address, active) values (398, 'Benjamen', 'Solna', true);
insert into STUDENTS (id, name, address, active) values (399, 'Orrin', 'Carigara', true);
insert into STUDENTS (id, name, address, active) values (400, 'Corey', 'Anrong', false);
insert into STUDENTS (id, name, address, active) values (401, 'Arabele', 'Tinaco', false);
insert into STUDENTS (id, name, address, active) values (402, 'Pollyanna', 'Vegachí', true);
insert into STUDENTS (id, name, address, active) values (403, 'Abner', 'Dongxi', true);
insert into STUDENTS (id, name, address, active) values (404, 'Catherina', 'Kostelec nad Černými Lesy', false);
insert into STUDENTS (id, name, address, active) values (405, 'Oralia', 'Anh Son', true);
insert into STUDENTS (id, name, address, active) values (406, 'Ollie', 'Presidente Epitácio', true);
insert into STUDENTS (id, name, address, active) values (407, 'Sarina', 'Bhokadoke', true);
insert into STUDENTS (id, name, address, active) values (408, 'Talia', 'Leonídio', false);
insert into STUDENTS (id, name, address, active) values (409, 'Pablo', 'Chigasaki', true);
insert into STUDENTS (id, name, address, active) values (410, 'Pierre', 'Pulupandan', true);
insert into STUDENTS (id, name, address, active) values (411, 'Arron', 'Nieuw Nickerie', true);
insert into STUDENTS (id, name, address, active) values (412, 'Kamillah', 'Carauari', true);
insert into STUDENTS (id, name, address, active) values (413, 'Clea', 'Tyre', false);
insert into STUDENTS (id, name, address, active) values (414, 'Adey', 'Vřesina', true);
insert into STUDENTS (id, name, address, active) values (415, 'Giustina', 'Xuri', true);
insert into STUDENTS (id, name, address, active) values (416, 'Pearle', 'Hezhai', true);
insert into STUDENTS (id, name, address, active) values (417, 'Edith', 'Menanga', true);
insert into STUDENTS (id, name, address, active) values (418, 'Garek', 'Varge Mondar', false);
insert into STUDENTS (id, name, address, active) values (419, 'Rollo', 'Xuanhuadian', true);
insert into STUDENTS (id, name, address, active) values (420, 'Vin', 'Santa Cruz', true);
insert into STUDENTS (id, name, address, active) values (421, 'Hyacinth', 'Berlin', false);
insert into STUDENTS (id, name, address, active) values (422, 'Angele', 'Três Passos', false);
insert into STUDENTS (id, name, address, active) values (423, 'Lacee', 'Athabasca', false);
insert into STUDENTS (id, name, address, active) values (424, 'Zorana', 'San Pedro Necta', true);
insert into STUDENTS (id, name, address, active) values (425, 'Rodrigo', 'Sanyang', true);
insert into STUDENTS (id, name, address, active) values (426, 'Rycca', 'Yafan', true);
insert into STUDENTS (id, name, address, active) values (427, 'Hayley', 'Luoting', false);
insert into STUDENTS (id, name, address, active) values (428, 'Guy', 'Ra-ngae', false);
insert into STUDENTS (id, name, address, active) values (429, 'Ravi', 'Cuauhtemoc', true);
insert into STUDENTS (id, name, address, active) values (430, 'Sianna', 'Port Antonio', false);
insert into STUDENTS (id, name, address, active) values (431, 'Dennet', 'Askainen', false);
insert into STUDENTS (id, name, address, active) values (432, 'Adolphus', 'Loei', true);
insert into STUDENTS (id, name, address, active) values (433, 'Laurie', 'Hacıqabul', false);
insert into STUDENTS (id, name, address, active) values (434, 'Justis', 'Kalān Deh', false);
insert into STUDENTS (id, name, address, active) values (435, 'Olive', 'Natividade', true);
insert into STUDENTS (id, name, address, active) values (436, 'Hoyt', 'Combita', false);
insert into STUDENTS (id, name, address, active) values (437, 'Hali', 'Dorotea', false);
insert into STUDENTS (id, name, address, active) values (438, 'Pammie', 'Teberda', false);
insert into STUDENTS (id, name, address, active) values (439, 'Serena', 'Gnojnik', false);
insert into STUDENTS (id, name, address, active) values (440, 'Vernon', 'Hulyaypole', false);
insert into STUDENTS (id, name, address, active) values (441, 'Sigfrid', 'Torre', false);
insert into STUDENTS (id, name, address, active) values (442, 'Tiphani', 'Hà Đông', true);
insert into STUDENTS (id, name, address, active) values (443, 'Correy', 'Mjölby', false);
insert into STUDENTS (id, name, address, active) values (444, 'Stirling', 'Ganhe', true);
insert into STUDENTS (id, name, address, active) values (445, 'Aaren', 'Boršice', false);
insert into STUDENTS (id, name, address, active) values (446, 'Foster', 'Xuwei', true);
insert into STUDENTS (id, name, address, active) values (447, 'Ayn', 'Coroico', true);
insert into STUDENTS (id, name, address, active) values (448, 'Edithe', 'Wuqishan', false);
insert into STUDENTS (id, name, address, active) values (449, 'Micky', 'Guantian', false);
insert into STUDENTS (id, name, address, active) values (450, 'Douglas', 'Khairiahmandah', true);
insert into STUDENTS (id, name, address, active) values (451, 'Rick', 'Ciawitali', true);
insert into STUDENTS (id, name, address, active) values (452, 'Alvera', 'Tegalalang', true);
insert into STUDENTS (id, name, address, active) values (453, 'Uri', 'Dongpu', true);
insert into STUDENTS (id, name, address, active) values (454, 'Gui', 'Italó', true);
insert into STUDENTS (id, name, address, active) values (455, 'Lemuel', 'Anyar', true);
insert into STUDENTS (id, name, address, active) values (456, 'Margaret', 'Petauke', true);
insert into STUDENTS (id, name, address, active) values (457, 'Saleem', 'Khombole', false);
insert into STUDENTS (id, name, address, active) values (458, 'Benn', 'Xiaogang', true);
insert into STUDENTS (id, name, address, active) values (459, 'Warren', 'Saint Andrews', true);
insert into STUDENTS (id, name, address, active) values (460, 'Staffard', 'Várzea de Sintra', false);
insert into STUDENTS (id, name, address, active) values (461, 'Karoline', 'Deán Funes', true);
insert into STUDENTS (id, name, address, active) values (462, 'Bevvy', 'Shijing', true);
insert into STUDENTS (id, name, address, active) values (463, 'Duky', 'Huaizhong', true);
insert into STUDENTS (id, name, address, active) values (464, 'Lory', 'Satovcha', false);
insert into STUDENTS (id, name, address, active) values (465, 'Jessica', 'Jatirejo', true);
insert into STUDENTS (id, name, address, active) values (466, 'Ferrell', 'Amnat Charoen', false);
insert into STUDENTS (id, name, address, active) values (467, 'Markos', 'Derviçian', false);
insert into STUDENTS (id, name, address, active) values (468, 'Gladi', 'Tengah', false);
insert into STUDENTS (id, name, address, active) values (469, 'Obadias', 'Curpahuasi', true);
insert into STUDENTS (id, name, address, active) values (470, 'Tilly', 'Pellegrini', false);
insert into STUDENTS (id, name, address, active) values (471, 'Alaric', 'Baranoa', false);
insert into STUDENTS (id, name, address, active) values (472, 'Jarvis', 'Werinama', false);
insert into STUDENTS (id, name, address, active) values (473, 'Mag', 'Chelu', false);
insert into STUDENTS (id, name, address, active) values (474, 'Daron', 'Croix', true);
insert into STUDENTS (id, name, address, active) values (475, 'Karia', 'Lombog', false);
insert into STUDENTS (id, name, address, active) values (476, 'Candis', 'Buriti Alegre', false);
insert into STUDENTS (id, name, address, active) values (477, 'Zorana', 'Tōkamachi', false);
insert into STUDENTS (id, name, address, active) values (478, 'Cammy', 'Puncakwangi', true);
insert into STUDENTS (id, name, address, active) values (479, 'Daloris', 'Lokoja', false);
insert into STUDENTS (id, name, address, active) values (480, 'Lin', 'Yershov', false);
insert into STUDENTS (id, name, address, active) values (481, 'Haslett', 'Woken', false);
insert into STUDENTS (id, name, address, active) values (482, 'Dagny', 'Birinci Aşıqlı', false);
insert into STUDENTS (id, name, address, active) values (483, 'Cinnamon', 'Xiachu', true);
insert into STUDENTS (id, name, address, active) values (484, 'Antonella', 'Heidelberg', true);
insert into STUDENTS (id, name, address, active) values (485, 'Toddy', 'Vetluga', false);
insert into STUDENTS (id, name, address, active) values (486, 'Honoria', 'Porvenir', true);
insert into STUDENTS (id, name, address, active) values (487, 'Kizzie', 'Ulaanbaatar', false);
insert into STUDENTS (id, name, address, active) values (488, 'Hermie', 'Wąwolnica', true);
insert into STUDENTS (id, name, address, active) values (489, 'Paquito', 'Loandjili', true);
insert into STUDENTS (id, name, address, active) values (490, 'Sherm', 'Iwata', true);
insert into STUDENTS (id, name, address, active) values (491, 'Annemarie', 'Chocz', false);
insert into STUDENTS (id, name, address, active) values (492, 'Fionnula', 'Colonia Nicolich', false);
insert into STUDENTS (id, name, address, active) values (493, 'Teddy', 'Las Vegas', false);
insert into STUDENTS (id, name, address, active) values (494, 'Leonid', 'Diébougou', false);
insert into STUDENTS (id, name, address, active) values (495, 'Riley', 'Hongsipu', false);
insert into STUDENTS (id, name, address, active) values (496, 'Armin', 'Casal Velho', false);
insert into STUDENTS (id, name, address, active) values (497, 'Rori', 'Umbanyar', true);
insert into STUDENTS (id, name, address, active) values (498, 'Malchy', 'Guisa', true);
insert into STUDENTS (id, name, address, active) values (499, 'Evyn', 'Darovskoy', true);
insert into STUDENTS (id, name, address, active) values (500, 'Klarrisa', 'Omaruru', false);
insert into STUDENTS (id, name, address, active) values (501, 'Andi', 'Xiangzikou', false);
insert into STUDENTS (id, name, address, active) values (502, 'Kimmie', 'Ishinomaki', false);
insert into STUDENTS (id, name, address, active) values (503, 'Rhodie', 'Bordeaux', false);
insert into STUDENTS (id, name, address, active) values (504, 'Katie', 'San Jacinto', true);
insert into STUDENTS (id, name, address, active) values (505, 'Hermine', 'Dmytrivka', true);
insert into STUDENTS (id, name, address, active) values (506, 'Katharina', 'Askim', true);
insert into STUDENTS (id, name, address, active) values (507, 'Kevon', 'Hengjing', false);
insert into STUDENTS (id, name, address, active) values (508, 'Peyter', 'Zopilotepe', false);
insert into STUDENTS (id, name, address, active) values (509, 'Winnie', 'Marseille', false);
insert into STUDENTS (id, name, address, active) values (510, 'Remington', 'Evansville', true);
insert into STUDENTS (id, name, address, active) values (511, 'Ware', 'Chantal', true);
insert into STUDENTS (id, name, address, active) values (512, 'Bentley', 'Caluya', false);
insert into STUDENTS (id, name, address, active) values (513, 'Honor', 'Hesi', true);
insert into STUDENTS (id, name, address, active) values (514, 'Wendy', 'Bassila', true);
insert into STUDENTS (id, name, address, active) values (515, 'Daren', 'Nazran’', false);
insert into STUDENTS (id, name, address, active) values (516, 'Kiah', 'Trat', false);
insert into STUDENTS (id, name, address, active) values (517, 'Damara', 'Hanyin Chengguanzhen', true);
insert into STUDENTS (id, name, address, active) values (518, 'Cordi', 'Aemura', true);
insert into STUDENTS (id, name, address, active) values (519, 'Jesse', 'Llorente', false);
insert into STUDENTS (id, name, address, active) values (520, 'Con', 'Tiaodeng', true);
insert into STUDENTS (id, name, address, active) values (521, 'Myrna', 'Burunday', true);
insert into STUDENTS (id, name, address, active) values (522, 'Mabelle', 'Spodnja Hajdina', false);
insert into STUDENTS (id, name, address, active) values (523, 'Madeleine', 'Zinat', true);
insert into STUDENTS (id, name, address, active) values (524, 'Giorgi', 'Aucallama', false);
insert into STUDENTS (id, name, address, active) values (525, 'Jo-anne', 'Katagum', true);
insert into STUDENTS (id, name, address, active) values (526, 'Catina', 'Nanzhihui', true);
insert into STUDENTS (id, name, address, active) values (527, 'Dar', 'Atiquizaya', false);
insert into STUDENTS (id, name, address, active) values (528, 'Brigitte', 'Sinegor''ye', false);
insert into STUDENTS (id, name, address, active) values (529, 'Hale', 'P’yŏngsŏng', true);
insert into STUDENTS (id, name, address, active) values (530, 'Errick', 'Maardu', true);
insert into STUDENTS (id, name, address, active) values (531, 'Jacky', 'Riosucio', true);
insert into STUDENTS (id, name, address, active) values (532, 'Myca', 'Diébougou', true);
insert into STUDENTS (id, name, address, active) values (533, 'Jdavie', 'La Soledad', true);
insert into STUDENTS (id, name, address, active) values (534, 'Rhea', 'Kamionka Strumitowa', false);
insert into STUDENTS (id, name, address, active) values (535, 'Eachelle', 'Bailizhou', false);
insert into STUDENTS (id, name, address, active) values (536, 'Margeaux', 'Dushanbe', false);
insert into STUDENTS (id, name, address, active) values (537, 'Rivalee', 'Innoshima', true);
insert into STUDENTS (id, name, address, active) values (538, 'Donn', 'Courtaboeuf', false);
insert into STUDENTS (id, name, address, active) values (539, 'Ivy', 'Oslo', false);
insert into STUDENTS (id, name, address, active) values (540, 'Charmine', 'Mae Sot', false);
insert into STUDENTS (id, name, address, active) values (541, 'Demetre', 'Gotse Delchev', false);
insert into STUDENTS (id, name, address, active) values (542, 'Carina', 'Pokachi', false);
insert into STUDENTS (id, name, address, active) values (543, 'Helge', 'Calzada Larga', false);
insert into STUDENTS (id, name, address, active) values (544, 'Aldric', 'Picton', true);
insert into STUDENTS (id, name, address, active) values (545, 'Sully', 'Lanshan', false);
insert into STUDENTS (id, name, address, active) values (546, 'Maurene', 'Lurugan', false);
insert into STUDENTS (id, name, address, active) values (547, 'Philbert', 'Bavorov', false);
insert into STUDENTS (id, name, address, active) values (548, 'Somerset', 'Podgorica', false);
insert into STUDENTS (id, name, address, active) values (549, 'Rhody', 'Imġarr', false);
insert into STUDENTS (id, name, address, active) values (550, 'Marty', 'Mayo', true);
insert into STUDENTS (id, name, address, active) values (551, 'Franky', 'Gumuk Tengah', false);
insert into STUDENTS (id, name, address, active) values (552, 'Devina', 'Aksu', false);
insert into STUDENTS (id, name, address, active) values (553, 'Reggy', 'Conceição da Feira', false);
insert into STUDENTS (id, name, address, active) values (554, 'Wilden', 'Talmest', false);
insert into STUDENTS (id, name, address, active) values (555, 'Ellerey', 'Carvalho', false);
insert into STUDENTS (id, name, address, active) values (556, 'Marlee', 'Sathing Phra', true);
insert into STUDENTS (id, name, address, active) values (557, 'Carlen', 'Bakar', false);
insert into STUDENTS (id, name, address, active) values (558, 'Etan', 'Tenja', true);
insert into STUDENTS (id, name, address, active) values (559, 'Sharon', 'Shilong', false);
insert into STUDENTS (id, name, address, active) values (560, 'Ruth', 'Calarcá', true);
insert into STUDENTS (id, name, address, active) values (561, 'Leroi', 'Jinnan', true);
insert into STUDENTS (id, name, address, active) values (562, 'Celie', 'Nha Trang', true);
insert into STUDENTS (id, name, address, active) values (563, 'Ambur', 'Portelândia', false);
insert into STUDENTS (id, name, address, active) values (564, 'Mirelle', 'Pivijay', false);
insert into STUDENTS (id, name, address, active) values (565, 'Dorice', 'Brengkok', false);
insert into STUDENTS (id, name, address, active) values (566, 'Venus', 'Zarechnyy', true);
insert into STUDENTS (id, name, address, active) values (567, 'Tarrance', 'Mellila', true);
insert into STUDENTS (id, name, address, active) values (568, 'Helenka', 'Saint Lucia', true);
insert into STUDENTS (id, name, address, active) values (569, 'Paten', 'Monamon', false);
insert into STUDENTS (id, name, address, active) values (570, 'Clarey', 'Cordon', false);
insert into STUDENTS (id, name, address, active) values (571, 'Horatia', 'Bengubelan', false);
insert into STUDENTS (id, name, address, active) values (572, 'Bryn', 'Rohia', true);
insert into STUDENTS (id, name, address, active) values (573, 'Ashbey', 'Loacan', true);
insert into STUDENTS (id, name, address, active) values (574, 'Cyrille', 'Chang’an', false);
insert into STUDENTS (id, name, address, active) values (575, 'Arlie', 'Golem', true);
insert into STUDENTS (id, name, address, active) values (576, 'Iago', 'Tanjungjaya', false);
insert into STUDENTS (id, name, address, active) values (577, 'Sophi', 'Buynaksk', false);
insert into STUDENTS (id, name, address, active) values (578, 'Roxanna', 'Montes Velhos', false);
insert into STUDENTS (id, name, address, active) values (579, 'Charlie', 'San Bernardo', true);
insert into STUDENTS (id, name, address, active) values (580, 'Rock', 'Huancheng', true);
insert into STUDENTS (id, name, address, active) values (581, 'Carmencita', 'Lidian', false);
insert into STUDENTS (id, name, address, active) values (582, 'Harmony', 'Tân Kỳ', true);
insert into STUDENTS (id, name, address, active) values (583, 'Edeline', 'Port Barton', false);
insert into STUDENTS (id, name, address, active) values (584, 'Dottie', 'Otofuke', true);
insert into STUDENTS (id, name, address, active) values (585, 'Jeremiah', 'Gongyi', false);
insert into STUDENTS (id, name, address, active) values (586, 'Ellerey', 'Březová nad Svitavou', false);
insert into STUDENTS (id, name, address, active) values (587, 'Baldwin', 'Vila Velha de Ródão', true);
insert into STUDENTS (id, name, address, active) values (588, 'Lyle', 'Naran Bulag', true);
insert into STUDENTS (id, name, address, active) values (589, 'Blane', 'Yuecheng', false);
insert into STUDENTS (id, name, address, active) values (590, 'Merwyn', 'Qīr Moāv', true);
insert into STUDENTS (id, name, address, active) values (591, 'Zollie', 'Shiqiao', false);
insert into STUDENTS (id, name, address, active) values (592, 'Ervin', 'Jiulong', false);
insert into STUDENTS (id, name, address, active) values (593, 'Klaus', 'Lewolere', false);
insert into STUDENTS (id, name, address, active) values (594, 'Alison', 'Oqtosh', true);
insert into STUDENTS (id, name, address, active) values (595, 'Corey', 'Spasskoye-Lutovinovo', false);
insert into STUDENTS (id, name, address, active) values (596, 'Ryley', 'Jiaoba', false);
insert into STUDENTS (id, name, address, active) values (597, 'Duncan', 'Quebradas', false);
insert into STUDENTS (id, name, address, active) values (598, 'Yves', 'Tyler', false);
insert into STUDENTS (id, name, address, active) values (599, 'Maia', 'Jiangqiao', true);
insert into STUDENTS (id, name, address, active) values (600, 'Rafaelita', 'Bojongsarung', true);
insert into STUDENTS (id, name, address, active) values (601, 'Nick', 'Cikubang', false);
insert into STUDENTS (id, name, address, active) values (602, 'Abel', 'Ágios Andréas', true);
insert into STUDENTS (id, name, address, active) values (603, 'Mabel', 'Thawat Buri', false);
insert into STUDENTS (id, name, address, active) values (604, 'Eduardo', 'Jardim do Seridó', true);
insert into STUDENTS (id, name, address, active) values (605, 'Anabal', 'Tianyu', false);
insert into STUDENTS (id, name, address, active) values (606, 'Pru', 'Marčelji', true);
insert into STUDENTS (id, name, address, active) values (607, 'Leigh', 'San Miguel', true);
insert into STUDENTS (id, name, address, active) values (608, 'Dunn', 'Piaski', false);
insert into STUDENTS (id, name, address, active) values (609, 'Erena', 'Vista Hermosa', false);
insert into STUDENTS (id, name, address, active) values (610, 'Dyan', 'Talondang', false);
insert into STUDENTS (id, name, address, active) values (611, 'Rhetta', 'Vasil’yevskiy Mokh', false);
insert into STUDENTS (id, name, address, active) values (612, 'Darsie', 'Vihti', false);
insert into STUDENTS (id, name, address, active) values (613, 'Xenos', 'Argelia', false);
insert into STUDENTS (id, name, address, active) values (614, 'Peadar', 'Talisay', false);
insert into STUDENTS (id, name, address, active) values (615, 'Trixi', 'Moyogalpa', true);
insert into STUDENTS (id, name, address, active) values (616, 'Corinna', 'Cuiabá', false);
insert into STUDENTS (id, name, address, active) values (617, 'Zorine', 'Mauren', true);
insert into STUDENTS (id, name, address, active) values (618, 'Jessie', 'Tandel', true);
insert into STUDENTS (id, name, address, active) values (619, 'Von', 'Marondera', false);
insert into STUDENTS (id, name, address, active) values (620, 'Timothee', 'Huoxian', true);
insert into STUDENTS (id, name, address, active) values (621, 'Bamby', 'Marinilla', true);
insert into STUDENTS (id, name, address, active) values (622, 'Julianne', 'Palanas', false);
insert into STUDENTS (id, name, address, active) values (623, 'Rubi', 'Lamadong', true);
insert into STUDENTS (id, name, address, active) values (624, 'Feodora', 'Hufeng', true);
insert into STUDENTS (id, name, address, active) values (625, 'Aldric', 'Were', false);
insert into STUDENTS (id, name, address, active) values (626, 'Thurston', 'Barinitas', true);
insert into STUDENTS (id, name, address, active) values (627, 'Vic', 'Vithkuq', false);
insert into STUDENTS (id, name, address, active) values (628, 'Samuel', 'Prengtale', false);
insert into STUDENTS (id, name, address, active) values (629, 'Ashlie', 'New York City', false);
insert into STUDENTS (id, name, address, active) values (630, 'Evita', 'Portelinha', true);
insert into STUDENTS (id, name, address, active) values (631, 'Ambros', 'Bendo', true);
insert into STUDENTS (id, name, address, active) values (632, 'Dannie', 'Sheffield', false);
insert into STUDENTS (id, name, address, active) values (633, 'Jaquenetta', 'Vargem Grande Paulista', false);
insert into STUDENTS (id, name, address, active) values (634, 'Merry', 'Taodian', true);
insert into STUDENTS (id, name, address, active) values (635, 'Ogdan', 'Beisijiazi', false);
insert into STUDENTS (id, name, address, active) values (636, 'Lorne', 'Saniwonorejo', true);
insert into STUDENTS (id, name, address, active) values (637, 'Harrison', 'Liugong', true);
insert into STUDENTS (id, name, address, active) values (638, 'Roxine', 'Shuizhai', true);
insert into STUDENTS (id, name, address, active) values (639, 'Gordon', 'Stepove', true);
insert into STUDENTS (id, name, address, active) values (640, 'Laurens', 'Kinlough', true);
insert into STUDENTS (id, name, address, active) values (641, 'Constantina', 'Baliuag Nuevo', false);
insert into STUDENTS (id, name, address, active) values (642, 'Noelle', 'Georgetown', true);
insert into STUDENTS (id, name, address, active) values (643, 'Deedee', 'Novyye Cherëmushki', false);
insert into STUDENTS (id, name, address, active) values (644, 'Germaine', 'Milano', false);
insert into STUDENTS (id, name, address, active) values (645, 'Aggy', 'Wanagiri', false);
insert into STUDENTS (id, name, address, active) values (646, 'Wolfy', 'Moguqi', false);
insert into STUDENTS (id, name, address, active) values (647, 'Cherilyn', 'Taozhuang', false);
insert into STUDENTS (id, name, address, active) values (648, 'Bessie', 'Kobleve', true);
insert into STUDENTS (id, name, address, active) values (649, 'Keene', 'Sangesi', false);
insert into STUDENTS (id, name, address, active) values (650, 'Cullen', 'Nkandla', true);
insert into STUDENTS (id, name, address, active) values (651, 'Silvano', 'La Purisima', false);
insert into STUDENTS (id, name, address, active) values (652, 'Wallis', 'Barrunchal', false);
insert into STUDENTS (id, name, address, active) values (653, 'Pren', 'Guri-si', false);
insert into STUDENTS (id, name, address, active) values (654, 'Kristan', 'Cholargós', false);
insert into STUDENTS (id, name, address, active) values (655, 'Rochelle', 'San Pedro de Macorís', true);
insert into STUDENTS (id, name, address, active) values (656, 'Kai', 'San Francisco', false);
insert into STUDENTS (id, name, address, active) values (657, 'Addie', 'Buliwao', true);
insert into STUDENTS (id, name, address, active) values (658, 'Cristin', 'Kizhinga', false);
insert into STUDENTS (id, name, address, active) values (659, 'Aldrich', 'Jingxi', false);
insert into STUDENTS (id, name, address, active) values (660, 'Shannah', 'San Cristóbal', false);
insert into STUDENTS (id, name, address, active) values (661, 'Bogart', 'Sho’rchi', true);
insert into STUDENTS (id, name, address, active) values (662, 'Cora', 'Abū Tīj', true);
insert into STUDENTS (id, name, address, active) values (663, 'Evin', 'Beruniy', true);
insert into STUDENTS (id, name, address, active) values (664, 'Lana', 'Adelaide Mail Centre', false);
insert into STUDENTS (id, name, address, active) values (665, 'Rasla', 'Omaha', true);
insert into STUDENTS (id, name, address, active) values (666, 'Nixie', 'Wichit', true);
insert into STUDENTS (id, name, address, active) values (667, 'Margy', 'Sukasenang', false);
insert into STUDENTS (id, name, address, active) values (668, 'Kandace', 'Muritiba', true);
insert into STUDENTS (id, name, address, active) values (669, 'Garfield', 'Hamhŭng', true);
insert into STUDENTS (id, name, address, active) values (670, 'Horatia', 'Hongshan', false);
insert into STUDENTS (id, name, address, active) values (671, 'Mord', 'Majennang', false);
insert into STUDENTS (id, name, address, active) values (672, 'Lukas', 'Gadzhiyevo', true);
insert into STUDENTS (id, name, address, active) values (673, 'Thomasin', 'Isahaya', false);
insert into STUDENTS (id, name, address, active) values (674, 'Merridie', 'Banaran', false);
insert into STUDENTS (id, name, address, active) values (675, 'Rickie', 'Cennan', true);
insert into STUDENTS (id, name, address, active) values (676, 'Odelia', 'Helin', true);
insert into STUDENTS (id, name, address, active) values (677, 'Druci', 'Dayushu', false);
insert into STUDENTS (id, name, address, active) values (678, 'Marybeth', 'Bahir Dar', true);
insert into STUDENTS (id, name, address, active) values (679, 'Evanne', 'Handa', true);
insert into STUDENTS (id, name, address, active) values (680, 'Kylie', 'Porto Alegre', true);
insert into STUDENTS (id, name, address, active) values (681, 'Eugine', 'An Nāşirīyah', false);
insert into STUDENTS (id, name, address, active) values (682, 'Pattin', 'Bacnotan', false);
insert into STUDENTS (id, name, address, active) values (683, 'Cesya', 'Columbia', true);
insert into STUDENTS (id, name, address, active) values (684, 'Sascha', 'Kuteynykove', false);
insert into STUDENTS (id, name, address, active) values (685, 'Kimble', 'Sukasari', false);
insert into STUDENTS (id, name, address, active) values (686, 'Lowell', 'Socabaya', false);
insert into STUDENTS (id, name, address, active) values (687, 'Andre', 'Bayan Gol', true);
insert into STUDENTS (id, name, address, active) values (688, 'Mata', 'Lincha', false);
insert into STUDENTS (id, name, address, active) values (689, 'Tim', 'Ngantru', true);
insert into STUDENTS (id, name, address, active) values (690, 'Lucila', 'Leskovec pri Krškem', false);
insert into STUDENTS (id, name, address, active) values (691, 'Pieter', 'Pytalovo', false);
insert into STUDENTS (id, name, address, active) values (692, 'Leann', 'Limanowa', true);
insert into STUDENTS (id, name, address, active) values (693, 'Elana', 'Slunj', true);
insert into STUDENTS (id, name, address, active) values (694, 'Daron', 'Lanipao', true);
insert into STUDENTS (id, name, address, active) values (695, 'Norbie', 'Licheń Stary', false);
insert into STUDENTS (id, name, address, active) values (696, 'Gwennie', 'Midland', true);
insert into STUDENTS (id, name, address, active) values (697, 'Caleb', 'Agriá', true);
insert into STUDENTS (id, name, address, active) values (698, 'Halimeda', 'Potrerillos Arriba', false);
insert into STUDENTS (id, name, address, active) values (699, 'Barclay', 'Dzhiginka', false);
insert into STUDENTS (id, name, address, active) values (700, 'Lara', 'Jiaobei', false);
insert into STUDENTS (id, name, address, active) values (701, 'Marla', 'Hukeng', true);
insert into STUDENTS (id, name, address, active) values (702, 'Nial', 'Sharīfābād', true);
insert into STUDENTS (id, name, address, active) values (703, 'Edyth', 'Taurage', true);
insert into STUDENTS (id, name, address, active) values (704, 'Bronny', 'Tatabánya', false);
insert into STUDENTS (id, name, address, active) values (705, 'Walden', 'Bajia', true);
insert into STUDENTS (id, name, address, active) values (706, 'Edie', 'Kurów', false);
insert into STUDENTS (id, name, address, active) values (707, 'Aveline', 'Bledzew', false);
insert into STUDENTS (id, name, address, active) values (708, 'Bebe', 'Gainesville', true);
insert into STUDENTS (id, name, address, active) values (709, 'Roxanna', 'Al Misrākh', false);
insert into STUDENTS (id, name, address, active) values (710, 'Jeremie', 'Obock', true);
insert into STUDENTS (id, name, address, active) values (711, 'Elberta', 'Sydney', false);
insert into STUDENTS (id, name, address, active) values (712, 'Dennis', 'Ehu', false);
insert into STUDENTS (id, name, address, active) values (713, 'Odetta', 'Montecristi', true);
insert into STUDENTS (id, name, address, active) values (714, 'Fey', 'Benjamín Aceval', false);
insert into STUDENTS (id, name, address, active) values (715, 'Regina', 'Arnoia', false);
insert into STUDENTS (id, name, address, active) values (716, 'Gillan', 'Figueiró dos Vinhos', true);
insert into STUDENTS (id, name, address, active) values (717, 'Kalie', 'Novorossiysk', true);
insert into STUDENTS (id, name, address, active) values (718, 'Bartholemy', 'Wairinding', false);
insert into STUDENTS (id, name, address, active) values (719, 'Lukas', 'Stockholm', true);
insert into STUDENTS (id, name, address, active) values (720, 'Pat', 'Dyurtyuli', false);
insert into STUDENTS (id, name, address, active) values (721, 'Patricia', 'Palmerston North', false);
insert into STUDENTS (id, name, address, active) values (722, 'Albina', 'Jincheng', true);
insert into STUDENTS (id, name, address, active) values (723, 'Chiquita', 'Santa Catalina', true);
insert into STUDENTS (id, name, address, active) values (724, 'Dolley', 'Shitouhe', true);
insert into STUDENTS (id, name, address, active) values (725, 'Miguela', 'Borovikha', true);
insert into STUDENTS (id, name, address, active) values (726, 'Cynthy', 'Zongzhai', true);
insert into STUDENTS (id, name, address, active) values (727, 'Heda', 'Paritjunus', true);
insert into STUDENTS (id, name, address, active) values (728, 'Noelle', 'Douane', false);
insert into STUDENTS (id, name, address, active) values (729, 'Sherri', 'Zhongzhai', false);
insert into STUDENTS (id, name, address, active) values (730, 'Charmain', 'Tarbagatay', true);
insert into STUDENTS (id, name, address, active) values (731, 'Cori', 'Bontang', true);
insert into STUDENTS (id, name, address, active) values (732, 'Channa', 'Langtang', true);
insert into STUDENTS (id, name, address, active) values (733, 'Minnaminnie', 'Prachin Buri', false);
insert into STUDENTS (id, name, address, active) values (734, 'Tirrell', 'Czarna', false);
insert into STUDENTS (id, name, address, active) values (735, 'Omero', 'Tečovice', false);
insert into STUDENTS (id, name, address, active) values (736, 'Lyda', 'Dungon', false);
insert into STUDENTS (id, name, address, active) values (737, 'Shelton', 'Ban Talat Nua', true);
insert into STUDENTS (id, name, address, active) values (738, 'Christalle', 'Panggungsari', true);
insert into STUDENTS (id, name, address, active) values (739, 'Baillie', 'Privodino', true);
insert into STUDENTS (id, name, address, active) values (740, 'Raynard', 'São Silvestre', true);
insert into STUDENTS (id, name, address, active) values (741, 'Colene', 'Nozdrzec', false);
insert into STUDENTS (id, name, address, active) values (742, 'Nancee', 'Getazat', false);
insert into STUDENTS (id, name, address, active) values (743, 'Gifford', 'Fort Worth', false);
insert into STUDENTS (id, name, address, active) values (744, 'Irvine', 'Malakwal City', true);
insert into STUDENTS (id, name, address, active) values (745, 'Carma', 'Lom Sak', true);
insert into STUDENTS (id, name, address, active) values (746, 'Ingrim', 'Mzimba', false);
insert into STUDENTS (id, name, address, active) values (747, 'Lidia', 'Montesson', false);
insert into STUDENTS (id, name, address, active) values (748, 'Klarrisa', 'Göteborg', false);
insert into STUDENTS (id, name, address, active) values (749, 'Idette', 'Quinta dos Frades', true);
insert into STUDENTS (id, name, address, active) values (750, 'Tarrah', 'Ferbane', true);
insert into STUDENTS (id, name, address, active) values (751, 'Ebeneser', 'San Pascual', true);
insert into STUDENTS (id, name, address, active) values (752, 'Leodora', 'Gampang', false);
insert into STUDENTS (id, name, address, active) values (753, 'Krystle', 'Santa Rita do Sapucaí', true);
insert into STUDENTS (id, name, address, active) values (754, 'Nadia', 'Baltasar Brum', true);
insert into STUDENTS (id, name, address, active) values (755, 'Kriste', 'St. Catharines', false);
insert into STUDENTS (id, name, address, active) values (756, 'Milli', 'Si Ma Cai', true);
insert into STUDENTS (id, name, address, active) values (757, 'Rhetta', 'Mitrópoli', true);
insert into STUDENTS (id, name, address, active) values (758, 'Terri', 'Kafir Yasif', false);
insert into STUDENTS (id, name, address, active) values (759, 'Jamie', 'Prosperous', false);
insert into STUDENTS (id, name, address, active) values (760, 'Nelson', 'Baixi', true);
insert into STUDENTS (id, name, address, active) values (761, 'Shelli', 'Jintao', false);
insert into STUDENTS (id, name, address, active) values (762, 'Warren', 'Jihui', false);
insert into STUDENTS (id, name, address, active) values (763, 'Zabrina', 'El Perico', false);
insert into STUDENTS (id, name, address, active) values (764, 'Peggi', 'Chillán', true);
insert into STUDENTS (id, name, address, active) values (765, 'Larine', 'Sanli', false);
insert into STUDENTS (id, name, address, active) values (766, 'Banky', 'Stari Bar', true);
insert into STUDENTS (id, name, address, active) values (767, 'Nessie', 'Is', true);
insert into STUDENTS (id, name, address, active) values (768, 'Aryn', 'Lorient', true);
insert into STUDENTS (id, name, address, active) values (769, 'Nan', 'Ponoka', false);
insert into STUDENTS (id, name, address, active) values (770, 'Danella', 'Köping', false);
insert into STUDENTS (id, name, address, active) values (771, 'Mano', 'Željezno Polje', false);
insert into STUDENTS (id, name, address, active) values (772, 'Adolphus', 'Maundai', false);
insert into STUDENTS (id, name, address, active) values (773, 'Rolph', 'Évry', false);
insert into STUDENTS (id, name, address, active) values (774, 'Algernon', 'Jiaokou', false);
insert into STUDENTS (id, name, address, active) values (775, 'Karel', 'Yasothon', true);
insert into STUDENTS (id, name, address, active) values (776, 'Mac', 'Słońsk', true);
insert into STUDENTS (id, name, address, active) values (777, 'Woodman', 'Lugo', false);
insert into STUDENTS (id, name, address, active) values (778, 'Dalston', 'Wenwusha', false);
insert into STUDENTS (id, name, address, active) values (779, 'Sheba', 'Socorro', false);
insert into STUDENTS (id, name, address, active) values (780, 'Halimeda', 'Tupaciguara', true);
insert into STUDENTS (id, name, address, active) values (781, 'Robby', 'Rosso', true);
insert into STUDENTS (id, name, address, active) values (782, 'Sherwood', 'Hucheng', true);
insert into STUDENTS (id, name, address, active) values (783, 'Kathe', 'Baisha', false);
insert into STUDENTS (id, name, address, active) values (784, 'Dianna', 'Succha', true);
insert into STUDENTS (id, name, address, active) values (785, 'Madge', 'Lasusua', true);
insert into STUDENTS (id, name, address, active) values (786, 'Klemens', 'Ježdovec', false);
insert into STUDENTS (id, name, address, active) values (787, 'Germain', 'Datagon', false);
insert into STUDENTS (id, name, address, active) values (788, 'Lucina', 'Le Mans', true);
insert into STUDENTS (id, name, address, active) values (789, 'Maggi', 'Constantia', false);
insert into STUDENTS (id, name, address, active) values (790, 'Daveta', 'Taodian', true);
insert into STUDENTS (id, name, address, active) values (791, 'Francesca', 'Austin', false);
insert into STUDENTS (id, name, address, active) values (792, 'Sherrie', 'Pacaraos', false);
insert into STUDENTS (id, name, address, active) values (793, 'Theresina', 'Salwá', false);
insert into STUDENTS (id, name, address, active) values (794, 'Esther', 'Cubará', false);
insert into STUDENTS (id, name, address, active) values (795, 'Robbie', 'Rayong', false);
insert into STUDENTS (id, name, address, active) values (796, 'Lindsy', 'Nacka', true);
insert into STUDENTS (id, name, address, active) values (797, 'Lane', 'Bantogon', true);
insert into STUDENTS (id, name, address, active) values (798, 'Jilleen', 'Lucan', true);
insert into STUDENTS (id, name, address, active) values (799, 'Sydel', 'Baiyang', true);
insert into STUDENTS (id, name, address, active) values (800, 'Gerianne', 'Niedercorn', true);
insert into STUDENTS (id, name, address, active) values (801, 'Eolande', 'Vidnoye', false);
insert into STUDENTS (id, name, address, active) values (802, 'Cherlyn', 'Předklášteří', true);
insert into STUDENTS (id, name, address, active) values (803, 'Wylma', 'Yermish’', true);
insert into STUDENTS (id, name, address, active) values (804, 'Auroora', 'Tílisos', true);
insert into STUDENTS (id, name, address, active) values (805, 'Nissa', 'Wang Muang', true);
insert into STUDENTS (id, name, address, active) values (806, 'Roobbie', 'Huansheng', true);
insert into STUDENTS (id, name, address, active) values (807, 'Analiese', 'Beauvais', true);
insert into STUDENTS (id, name, address, active) values (808, 'Weston', 'Krikil', true);
insert into STUDENTS (id, name, address, active) values (809, 'Barclay', 'Türkmenbaşy', true);
insert into STUDENTS (id, name, address, active) values (810, 'Tessi', 'Yongping', false);
insert into STUDENTS (id, name, address, active) values (811, 'Bar', 'Valenciennes', false);
insert into STUDENTS (id, name, address, active) values (812, 'Gaspar', 'Shahrak', false);
insert into STUDENTS (id, name, address, active) values (813, 'Marrilee', 'Paraisópolis', false);
insert into STUDENTS (id, name, address, active) values (814, 'Catina', 'Thị Trấn Nguyên Bình', false);
insert into STUDENTS (id, name, address, active) values (815, 'Tan', 'Aricagua', false);
insert into STUDENTS (id, name, address, active) values (816, 'Maisie', 'Lingzhi', false);
insert into STUDENTS (id, name, address, active) values (817, 'Wendell', 'Mangaran', false);
insert into STUDENTS (id, name, address, active) values (818, 'Neal', 'Soledad', true);
insert into STUDENTS (id, name, address, active) values (819, 'Burty', 'Longmenfan', true);
insert into STUDENTS (id, name, address, active) values (820, 'Enrika', 'Imotski', true);
insert into STUDENTS (id, name, address, active) values (821, 'Garret', 'Pavlysh', false);
insert into STUDENTS (id, name, address, active) values (822, 'Jarret', 'Kuncen', true);
insert into STUDENTS (id, name, address, active) values (823, 'Yvon', 'Yizhivtsi', true);
insert into STUDENTS (id, name, address, active) values (824, 'Rosetta', 'Tlogosari', true);
insert into STUDENTS (id, name, address, active) values (825, 'Bambie', 'Las Palmas', true);
insert into STUDENTS (id, name, address, active) values (826, 'Hobard', 'Pampas Chico', false);
insert into STUDENTS (id, name, address, active) values (827, 'Pavlov', 'Maloyaroslavets', true);
insert into STUDENTS (id, name, address, active) values (828, 'Lorry', 'Piteå', false);
insert into STUDENTS (id, name, address, active) values (829, 'Shelia', 'Batulawang', false);
insert into STUDENTS (id, name, address, active) values (830, 'Aliza', 'Barurao', true);
insert into STUDENTS (id, name, address, active) values (831, 'Oliver', 'Talisay', true);
insert into STUDENTS (id, name, address, active) values (832, 'Hephzibah', 'Chantilly', true);
insert into STUDENTS (id, name, address, active) values (833, 'Abbey', 'Washington', true);
insert into STUDENTS (id, name, address, active) values (834, 'Ellis', 'Shangani', false);
insert into STUDENTS (id, name, address, active) values (835, 'Bevon', 'Cankuzo', true);
insert into STUDENTS (id, name, address, active) values (836, 'Natty', 'Wuyang', true);
insert into STUDENTS (id, name, address, active) values (837, 'Pat', 'Wuxiang', true);
insert into STUDENTS (id, name, address, active) values (838, 'Mile', 'Yengimahalla', true);
insert into STUDENTS (id, name, address, active) values (839, 'Celia', 'Salinas', false);
insert into STUDENTS (id, name, address, active) values (840, 'Lydon', 'Bode Sadu', false);
insert into STUDENTS (id, name, address, active) values (841, 'Corbett', 'Lukavec', true);
insert into STUDENTS (id, name, address, active) values (842, 'Alonso', 'Cahors', true);
insert into STUDENTS (id, name, address, active) values (843, 'Sheree', 'Heshi', true);
insert into STUDENTS (id, name, address, active) values (844, 'Margarette', 'Taosha', true);
insert into STUDENTS (id, name, address, active) values (845, 'Donny', 'Pangpang', true);
insert into STUDENTS (id, name, address, active) values (846, 'Natty', 'Carmen', true);
insert into STUDENTS (id, name, address, active) values (847, 'Scarlett', 'Hino', true);
insert into STUDENTS (id, name, address, active) values (848, 'Nehemiah', 'Wolfville', false);
insert into STUDENTS (id, name, address, active) values (849, 'Dorothea', 'Bagou', true);
insert into STUDENTS (id, name, address, active) values (850, 'Sarajane', 'Rancaseneng', false);
insert into STUDENTS (id, name, address, active) values (851, 'Edgar', 'Pingli', false);
insert into STUDENTS (id, name, address, active) values (852, 'Louisette', 'Yujin', true);
insert into STUDENTS (id, name, address, active) values (853, 'Yvonne', 'Pariti', true);
insert into STUDENTS (id, name, address, active) values (854, 'Karney', 'Punkalaidun', true);
insert into STUDENTS (id, name, address, active) values (855, 'Clemens', 'Roche Terre', false);
insert into STUDENTS (id, name, address, active) values (856, 'Jeana', 'Nanaimo', false);
insert into STUDENTS (id, name, address, active) values (857, 'Elva', 'Sumaré', true);
insert into STUDENTS (id, name, address, active) values (858, 'Desdemona', 'Paarl', true);
insert into STUDENTS (id, name, address, active) values (859, 'Catie', 'Clearwater', true);
insert into STUDENTS (id, name, address, active) values (860, 'Krishna', 'Lysekil', false);
insert into STUDENTS (id, name, address, active) values (861, 'Chase', 'Ea Drăng', true);
insert into STUDENTS (id, name, address, active) values (862, 'Polly', 'Brampton', true);
insert into STUDENTS (id, name, address, active) values (863, 'Farley', 'Bājitpur', false);
insert into STUDENTS (id, name, address, active) values (864, 'Nolly', 'Lansing', false);
insert into STUDENTS (id, name, address, active) values (865, 'Latrena', 'Sabugueiro', true);
insert into STUDENTS (id, name, address, active) values (866, 'Marne', 'Concepción', true);
insert into STUDENTS (id, name, address, active) values (867, 'Liesa', 'Río Segundo', false);
insert into STUDENTS (id, name, address, active) values (868, 'Keefe', 'Göteborg', false);
insert into STUDENTS (id, name, address, active) values (869, 'Kristy', 'Villaguay', false);
insert into STUDENTS (id, name, address, active) values (870, 'Giuditta', 'Petroúpolis', true);
insert into STUDENTS (id, name, address, active) values (871, 'Langston', 'Bennäs', true);
insert into STUDENTS (id, name, address, active) values (872, 'Emilie', 'Jastrowie', false);
insert into STUDENTS (id, name, address, active) values (873, 'Monah', 'Zhaojia', true);
insert into STUDENTS (id, name, address, active) values (874, 'Branden', 'La Roche-sur-Yon', false);
insert into STUDENTS (id, name, address, active) values (875, 'Agathe', 'Altamira', true);
insert into STUDENTS (id, name, address, active) values (876, 'Phaedra', 'Pingling', false);
insert into STUDENTS (id, name, address, active) values (877, 'Broddy', 'Sanban', true);
insert into STUDENTS (id, name, address, active) values (878, 'Nicoli', 'Sidoger Lebak', false);
insert into STUDENTS (id, name, address, active) values (879, 'Leonardo', 'Hénin-Beaumont', false);
insert into STUDENTS (id, name, address, active) values (880, 'Neilla', 'La Unión', true);
insert into STUDENTS (id, name, address, active) values (881, 'Shep', 'Unisław', false);
insert into STUDENTS (id, name, address, active) values (882, 'Esteban', 'Georgiyevsk', true);
insert into STUDENTS (id, name, address, active) values (883, 'Toma', 'Jinjiang', true);
insert into STUDENTS (id, name, address, active) values (884, 'Dacie', 'Fuming', false);
insert into STUDENTS (id, name, address, active) values (885, 'Bram', 'Aiguo', false);
insert into STUDENTS (id, name, address, active) values (886, 'Mignonne', 'Halat', false);
insert into STUDENTS (id, name, address, active) values (887, 'Wendeline', 'Damaying', true);
insert into STUDENTS (id, name, address, active) values (888, 'Shanna', 'Dawu', false);
insert into STUDENTS (id, name, address, active) values (889, 'Khalil', 'Guifeng', false);
insert into STUDENTS (id, name, address, active) values (890, 'Gabby', 'Misasi', false);
insert into STUDENTS (id, name, address, active) values (891, 'Clive', 'San Isidro', true);
insert into STUDENTS (id, name, address, active) values (892, 'Bertha', 'Wichita', true);
insert into STUDENTS (id, name, address, active) values (893, 'Melania', 'Oslob', true);
insert into STUDENTS (id, name, address, active) values (894, 'Sherilyn', 'Amargosa', false);
insert into STUDENTS (id, name, address, active) values (895, 'Brendis', 'Palompon', true);
insert into STUDENTS (id, name, address, active) values (896, 'Gannie', 'Poxi', true);
insert into STUDENTS (id, name, address, active) values (897, 'Christy', 'Helsingborg', false);
insert into STUDENTS (id, name, address, active) values (898, 'Holli', 'Bornu Yassu', false);
insert into STUDENTS (id, name, address, active) values (899, 'Sallyanne', 'Murów', true);
insert into STUDENTS (id, name, address, active) values (900, 'Zacharie', 'Ubon Ratchathani', true);
insert into STUDENTS (id, name, address, active) values (901, 'Doreen', 'Ilhabela', false);
insert into STUDENTS (id, name, address, active) values (902, 'Robin', 'Bratislava', false);
insert into STUDENTS (id, name, address, active) values (903, 'Thomas', 'Ábrego', true);
insert into STUDENTS (id, name, address, active) values (904, 'Reagan', 'Koroška Bela', true);
insert into STUDENTS (id, name, address, active) values (905, 'Erny', 'Alcáçovas', true);
insert into STUDENTS (id, name, address, active) values (906, 'Joline', 'Kuala Terengganu', true);
insert into STUDENTS (id, name, address, active) values (907, 'Staford', 'San Luis del Palmar', false);
insert into STUDENTS (id, name, address, active) values (908, 'Ethel', 'Levuka', false);
insert into STUDENTS (id, name, address, active) values (909, 'Ingeberg', 'Puteaux', true);
insert into STUDENTS (id, name, address, active) values (910, 'Wallace', 'Popovo', true);
insert into STUDENTS (id, name, address, active) values (911, 'Gerald', 'Gaphatshwe', true);
insert into STUDENTS (id, name, address, active) values (912, 'Saree', 'Guanyinsi', true);
insert into STUDENTS (id, name, address, active) values (913, 'Sashenka', 'Tongbang', true);
insert into STUDENTS (id, name, address, active) values (914, 'Bertram', 'Benger', false);
insert into STUDENTS (id, name, address, active) values (915, 'Clarita', 'Bulog', false);
insert into STUDENTS (id, name, address, active) values (916, 'Timmy', 'Kalávryta', false);
insert into STUDENTS (id, name, address, active) values (917, 'Octavia', 'Kompóti', false);
insert into STUDENTS (id, name, address, active) values (918, 'Jude', 'Jember', true);
insert into STUDENTS (id, name, address, active) values (919, 'Thorstein', 'Boudinar', true);
insert into STUDENTS (id, name, address, active) values (920, 'Margarette', 'Maodian', false);
insert into STUDENTS (id, name, address, active) values (921, 'Man', 'Kvasiny', false);
insert into STUDENTS (id, name, address, active) values (922, 'Sherline', 'Hyesan-dong', true);
insert into STUDENTS (id, name, address, active) values (923, 'Holly-anne', 'Wałcz', false);
insert into STUDENTS (id, name, address, active) values (924, 'Inge', 'Lewograran', true);
insert into STUDENTS (id, name, address, active) values (925, 'Dory', 'Bačka Topola', false);
insert into STUDENTS (id, name, address, active) values (926, 'Ilsa', 'Dongjin', true);
insert into STUDENTS (id, name, address, active) values (927, 'Caressa', 'Ejidal', true);
insert into STUDENTS (id, name, address, active) values (928, 'Christel', 'Shreveport', true);
insert into STUDENTS (id, name, address, active) values (929, 'Anetta', 'Kista', false);
insert into STUDENTS (id, name, address, active) values (930, 'Tina', 'Dengfeng', false);
insert into STUDENTS (id, name, address, active) values (931, 'Raimundo', 'Choibalsan', false);
insert into STUDENTS (id, name, address, active) values (932, 'Kirby', 'Pizarrete', true);
insert into STUDENTS (id, name, address, active) values (933, 'Engelbert', 'Shengmi', false);
insert into STUDENTS (id, name, address, active) values (934, 'Leola', 'Pueblo Nuevo', true);
insert into STUDENTS (id, name, address, active) values (935, 'Melantha', 'Sholokhove', false);
insert into STUDENTS (id, name, address, active) values (936, 'Vittorio', 'Huayacundo Arma', true);
insert into STUDENTS (id, name, address, active) values (937, 'Muffin', 'Stoczek', false);
insert into STUDENTS (id, name, address, active) values (938, 'Milicent', 'Belyye Stolby', true);
insert into STUDENTS (id, name, address, active) values (939, 'Goran', 'Kayes', false);
insert into STUDENTS (id, name, address, active) values (940, 'Emmalynn', 'Ning’an', true);
insert into STUDENTS (id, name, address, active) values (941, 'Dionisio', 'Mmaaf', true);
insert into STUDENTS (id, name, address, active) values (942, 'Felicity', 'Osh', true);
insert into STUDENTS (id, name, address, active) values (943, 'Heath', 'Mönchengladbach', true);
insert into STUDENTS (id, name, address, active) values (944, 'Cordelia', 'Lahishyn', false);
insert into STUDENTS (id, name, address, active) values (945, 'Eleanore', 'Lutoryż', false);
insert into STUDENTS (id, name, address, active) values (946, 'Pia', 'Espírito Santo do Pinhal', false);
insert into STUDENTS (id, name, address, active) values (947, 'Benjy', 'Xiaoshanzi', false);
insert into STUDENTS (id, name, address, active) values (948, 'Vance', 'Oudtshoorn', true);
insert into STUDENTS (id, name, address, active) values (949, 'Merrielle', 'Hadano', false);
insert into STUDENTS (id, name, address, active) values (950, 'Clywd', 'Old Kilcullen', false);
insert into STUDENTS (id, name, address, active) values (951, 'Aura', 'Łęki', false);
insert into STUDENTS (id, name, address, active) values (952, 'Brena', 'Shangxing', false);
insert into STUDENTS (id, name, address, active) values (953, 'Moore', 'Sandefjord', true);
insert into STUDENTS (id, name, address, active) values (954, 'Blaire', 'Al Jabīn', false);
insert into STUDENTS (id, name, address, active) values (955, 'Maressa', 'Shakhun’ya', true);
insert into STUDENTS (id, name, address, active) values (956, 'Emelyne', 'Muara', false);
insert into STUDENTS (id, name, address, active) values (957, 'Valina', 'Malusac', true);
insert into STUDENTS (id, name, address, active) values (958, 'Eugenia', 'Krugersdorp', false);
insert into STUDENTS (id, name, address, active) values (959, 'Norbert', 'Brody', false);
insert into STUDENTS (id, name, address, active) values (960, 'Marilin', 'Paritaman', false);
insert into STUDENTS (id, name, address, active) values (961, 'Aleta', 'Jakobstad', false);
insert into STUDENTS (id, name, address, active) values (962, 'Gaby', 'Cañasgordas', false);
insert into STUDENTS (id, name, address, active) values (963, 'Kimmi', 'Inírida', true);
insert into STUDENTS (id, name, address, active) values (964, 'Kathi', 'Quimperlé', true);
insert into STUDENTS (id, name, address, active) values (965, 'Sammy', 'Baleal', false);
insert into STUDENTS (id, name, address, active) values (966, 'Valenka', 'Medicine Hat', false);
insert into STUDENTS (id, name, address, active) values (967, 'Ava', 'Coromandel', true);
insert into STUDENTS (id, name, address, active) values (968, 'Sibelle', 'Kepoh', true);
insert into STUDENTS (id, name, address, active) values (969, 'Garrett', 'Tervel', true);
insert into STUDENTS (id, name, address, active) values (970, 'Christean', 'Mýrina', false);
insert into STUDENTS (id, name, address, active) values (971, 'Alina', 'Yaroslavskiy', true);
insert into STUDENTS (id, name, address, active) values (972, 'Daren', 'Senovo', false);
insert into STUDENTS (id, name, address, active) values (973, 'Harp', 'Hamar', false);
insert into STUDENTS (id, name, address, active) values (974, 'Jobey', 'Livramento do Brumado', false);
insert into STUDENTS (id, name, address, active) values (975, 'Cortie', 'Morales', true);
insert into STUDENTS (id, name, address, active) values (976, 'Ephrayim', 'Mineralnye Vody', false);
insert into STUDENTS (id, name, address, active) values (977, 'Wileen', 'Fuente de Oro', true);
insert into STUDENTS (id, name, address, active) values (978, 'Felice', 'Fagersta', false);
insert into STUDENTS (id, name, address, active) values (979, 'Rosita', 'Corral de Bustos', false);
insert into STUDENTS (id, name, address, active) values (980, 'Ludovico', 'Knurów', false);
insert into STUDENTS (id, name, address, active) values (981, 'Conroy', 'Enonkoski', false);
insert into STUDENTS (id, name, address, active) values (982, 'Donni', 'Zhaoxiang', true);
insert into STUDENTS (id, name, address, active) values (983, 'Mathew', 'Xinfeng', true);
insert into STUDENTS (id, name, address, active) values (984, 'Suzy', 'Yangjiao', true);
insert into STUDENTS (id, name, address, active) values (985, 'Kayne', 'Shreveport', true);
insert into STUDENTS (id, name, address, active) values (986, 'Paul', 'Odrinhas', true);
insert into STUDENTS (id, name, address, active) values (987, 'Colene', 'Bungoma', false);
insert into STUDENTS (id, name, address, active) values (988, 'Merci', 'Karangtalun', false);
insert into STUDENTS (id, name, address, active) values (989, 'Bengt', 'Krynychky', true);
insert into STUDENTS (id, name, address, active) values (990, 'Nerita', 'Mora', true);
insert into STUDENTS (id, name, address, active) values (991, 'Abbey', 'Thị Trấn Thất Khê', false);
insert into STUDENTS (id, name, address, active) values (992, 'Gisela', 'Sobreira', true);
insert into STUDENTS (id, name, address, active) values (993, 'Alexandros', 'Colorado Springs', true);
insert into STUDENTS (id, name, address, active) values (994, 'Editha', 'Shashūbay', true);
insert into STUDENTS (id, name, address, active) values (995, 'Michal', 'Kozel’shchyna', false);
insert into STUDENTS (id, name, address, active) values (996, 'Correna', 'Jiangshan', true);
insert into STUDENTS (id, name, address, active) values (997, 'Charlie', 'Lynchburg', false);
insert into STUDENTS (id, name, address, active) values (998, 'Carroll', 'Bechlín', false);
insert into STUDENTS (id, name, address, active) values (999, 'Armin', 'Zhaogezhuang', false);
insert into STUDENTS (id, name, address, active) values (1000, 'Ronalda', 'Caen', true);

update students set created_on=now();
